### PR TITLE
Add section documenting tags.

### PR DESCRIPTION
**Pull request by alysbrooks**
I don't think people realize you can do this, particularly people like me who are unfamiliar with Gherkin syntax due to never having used the original Ruby version of Cucumber.

### CODE REVIEW

**Comment by plexus** [comment]
@alysbrooks did you forget to add a file? I don't see any documentation changes in this PR, only a change to the parallel test runner.

**Comment by alysbrooks** [comment]
@plexus Hmm, not sure where these changes went. I think I'll have to recreate them, unfortunately.

**Comment by alysbrooks** [comment]
This is a pretty small change, so I'm just going to go ahead and merge.

**Comment by alysbrooks** [comment]
Released in [v0.1.84](https://github.com/lambdaisland/kaocha-cucumber/releases/tag/v0.1.84)

```clj
[com.lambdaisland/kaocha-cucumber "0.1.84"]                 ;; deps.edn
{com.lambdaisland/kaocha-cucumber {:mvn/version "0.1.84"}}  ;; project.clj
```

**Pull request merged**
