### PR TITLE
Adds type annotations so that reflection warnings are prevented.

### PR DESCRIPTION
**Pull request by mapidentity**
See issue https://github.com/lambdaisland/kaocha-cucumber/issues/3

When code under test contains `(set! *warn-on-reflection* true)` the output contains reflection warnings from the kaocha-cucumber namespace. This PR adds type annotations so these warnings are prevented.

Feedback is greatly appreciated.

### CODE REVIEW

**Comment by plexus** [comment]
Thanks!

**Comment by plexus** [comment]
```
Clojure 1.10.1
user=> (require 'lambdaisland.cucumber.gherkin)
Syntax error (NoSuchFieldException) compiling . at (lambdaisland/cucumber/jvm.clj:156:34).
of
```

Seems `List/of` is problematic.

**Comment by plexus** [comment]
Found a fix, releasing as `kaocha-cucumber "0.0-53"`. Thanks for the patch!

**Comment by alysbrooks** [comment]
Released in [v0.1.84](https://github.com/lambdaisland/kaocha-cucumber/releases/tag/v0.1.84)

```clj
[com.lambdaisland/kaocha-cucumber "0.1.84"]                 ;; deps.edn
{com.lambdaisland/kaocha-cucumber {:mvn/version "0.1.84"}}  ;; project.clj
```

**Pull request merged**
